### ISSUE TITLE
React Embed generates duplicated iframes

### ISSUE THREAD

**Issue by idoliki** [formsort/oss#72]
### How to reproduce:
1. Create NextJS app with `npx create-next-app`
2. Install React Embed pkg with `npm i @formsort/react-embed`
3. Load the EmbedFlow as per documentation https://github.com/formsort/oss/tree/master/packages/react-embed
4. The wrapper creates duplicated iframe nodes
![Screenshot 2022-06-20 at 14 36 29](https://user-images.githubusercontent.com/7974311/174603131-2d95acb5-3da0-46ba-ba52-397687cb796f.png)

### Cause
This is due to React 18 in Strict mode with its double render.

### Workaround
- Downgrade to React 17
- Remove Strict mode on React 18
- Using the @formsort/web-embed-api and using ref to make sure it only loads once

### Implementation
Implement on the react wrapper (react-embed pkg) the ref object to make sure it only loads once.

for example:
![Screenshot 2022-06-20 at 15 13 52](https://user-images.githubusercontent.com/7974311/174610024-1434854f-ac25-482e-93b0-28a5fd55e8d9.png)

Or add a proper cleanup function:
https://beta.reactjs.org/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development

**Comment by lizraeli** [comment]
@idoliki thank you for reporting this issue! We will look into fixing this.
